# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceOC.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 850))
        MainWindow.setMaximumSize(QtCore.QSize(700, 850))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setEnabled(False)
        self.line.setGeometry(QtCore.QRect(160, 0, 20, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 360, 691, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Crafter_lab = QtWidgets.QLabel(self.centralwidget)
        self.Crafter_lab.setGeometry(QtCore.QRect(50, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Crafter_lab.setFont(font)
        self.Crafter_lab.setObjectName("Crafter_lab")
        self.BluePrint_lab = QtWidgets.QLabel(self.centralwidget)
        self.BluePrint_lab.setGeometry(QtCore.QRect(220, 0, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BluePrint_lab.setFont(font)
        self.BluePrint_lab.setObjectName("BluePrint_lab")
        self.INTQt = QtWidgets.QSpinBox(self.centralwidget)
        self.INTQt.setEnabled(False)
        self.INTQt.setGeometry(QtCore.QRect(60, 90, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INTQt.setFont(font)
        self.INTQt.setMinimum(1)
        self.INTQt.setMaximum(5)
        self.INTQt.setObjectName("INTQt")
        self.CRFTQt = QtWidgets.QSpinBox(self.centralwidget)
        self.CRFTQt.setEnabled(False)
        self.CRFTQt.setGeometry(QtCore.QRect(60, 120, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CRFTQt.setFont(font)
        self.CRFTQt.setMaximum(5)
        self.CRFTQt.setObjectName("CRFTQt")
        self.SINCQt = QtWidgets.QSpinBox(self.centralwidget)
        self.SINCQt.setEnabled(False)
        self.SINCQt.setGeometry(QtCore.QRect(60, 150, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SINCQt.setFont(font)
        self.SINCQt.setMaximum(5)
        self.SINCQt.setObjectName("SINCQt")
        self.INT_lab = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab.setEnabled(True)
        self.INT_lab.setGeometry(QtCore.QRect(30, 90, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab.setFont(font)
        self.INT_lab.setObjectName("INT_lab")
        self.Craft_lab = QtWidgets.QLabel(self.centralwidget)
        self.Craft_lab.setEnabled(True)
        self.Craft_lab.setGeometry(QtCore.QRect(20, 120, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Craft_lab.setFont(font)
        self.Craft_lab.setObjectName("Craft_lab")
        self.Since_lab = QtWidgets.QLabel(self.centralwidget)
        self.Since_lab.setEnabled(True)
        self.Since_lab.setGeometry(QtCore.QRect(20, 150, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Since_lab.setFont(font)
        self.Since_lab.setObjectName("Since_lab")
        self.Computer_lab = QtWidgets.QLabel(self.centralwidget)
        self.Computer_lab.setEnabled(True)
        self.Computer_lab.setGeometry(QtCore.QRect(0, 180, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Computer_lab.setFont(font)
        self.Computer_lab.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Computer_lab.setObjectName("Computer_lab")
        self.COMPQt = QtWidgets.QSpinBox(self.centralwidget)
        self.COMPQt.setEnabled(False)
        self.COMPQt.setGeometry(QtCore.QRect(60, 180, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.COMPQt.setFont(font)
        self.COMPQt.setMaximum(5)
        self.COMPQt.setObjectName("COMPQt")
        self.TYQt = QtWidgets.QSpinBox(self.centralwidget)
        self.TYQt.setEnabled(False)
        self.TYQt.setGeometry(QtCore.QRect(200, 30, 31, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TYQt.setFont(font)
        self.TYQt.setMinimum(1)
        self.TYQt.setMaximum(7)
        self.TYQt.setProperty("value", 1)
        self.TYQt.setObjectName("TYQt")
        self.INT_lab_2 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_2.setEnabled(True)
        self.INT_lab_2.setGeometry(QtCore.QRect(180, 30, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_2.setFont(font)
        self.INT_lab_2.setObjectName("INT_lab_2")
        self.RQt = QtWidgets.QSpinBox(self.centralwidget)
        self.RQt.setEnabled(False)
        self.RQt.setGeometry(QtCore.QRect(180, 70, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RQt.setFont(font)
        self.RQt.setMinimum(1)
        self.RQt.setMaximum(50)
        self.RQt.setObjectName("RQt")
        self.INT_lab_3 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_3.setEnabled(True)
        self.INT_lab_3.setGeometry(QtCore.QRect(180, 50, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_3.setFont(font)
        self.INT_lab_3.setObjectName("INT_lab_3")
        self.STRQt = QtWidgets.QSpinBox(self.centralwidget)
        self.STRQt.setEnabled(False)
        self.STRQt.setGeometry(QtCore.QRect(310, 70, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.STRQt.setFont(font)
        self.STRQt.setMinimum(1)
        self.STRQt.setMaximum(7)
        self.STRQt.setObjectName("STRQt")
        self.INT_lab_4 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_4.setEnabled(True)
        self.INT_lab_4.setGeometry(QtCore.QRect(280, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_4.setFont(font)
        self.INT_lab_4.setObjectName("INT_lab_4")
        self.OMMQt = QtWidgets.QSpinBox(self.centralwidget)
        self.OMMQt.setEnabled(False)
        self.OMMQt.setGeometry(QtCore.QRect(370, 110, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OMMQt.setFont(font)
        self.OMMQt.setMaximum(5)
        self.OMMQt.setObjectName("OMMQt")
        self.INT_lab_5 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_5.setEnabled(True)
        self.INT_lab_5.setGeometry(QtCore.QRect(340, 110, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_5.setFont(font)
        self.INT_lab_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.INT_lab_5.setObjectName("INT_lab_5")
        self.OMRQt = QtWidgets.QSpinBox(self.centralwidget)
        self.OMRQt.setEnabled(False)
        self.OMRQt.setGeometry(QtCore.QRect(370, 140, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OMRQt.setFont(font)
        self.OMRQt.setMaximum(5)
        self.OMRQt.setObjectName("OMRQt")
        self.INT_lab_6 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_6.setEnabled(True)
        self.INT_lab_6.setGeometry(QtCore.QRect(340, 140, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_6.setFont(font)
        self.INT_lab_6.setObjectName("INT_lab_6")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setEnabled(False)
        self.line_3.setGeometry(QtCore.QRect(310, 120, 20, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.INT_lab_7 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_7.setEnabled(True)
        self.INT_lab_7.setGeometry(QtCore.QRect(240, 30, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_7.setFont(font)
        self.INT_lab_7.setObjectName("INT_lab_7")
        self.INT_lab_8 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_8.setEnabled(True)
        self.INT_lab_8.setGeometry(QtCore.QRect(280, 180, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_8.setFont(font)
        self.INT_lab_8.setObjectName("INT_lab_8")
        self.INT_lab_9 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_9.setEnabled(True)
        self.INT_lab_9.setGeometry(QtCore.QRect(230, 70, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_9.setFont(font)
        self.INT_lab_9.setObjectName("INT_lab_9")
        self.OM = QtWidgets.QLabel(self.centralwidget)
        self.OM.setEnabled(True)
        self.OM.setGeometry(QtCore.QRect(190, 120, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OM.setFont(font)
        self.OM.setObjectName("OM")
        self.OMQt = QtWidgets.QSpinBox(self.centralwidget)
        self.OMQt.setEnabled(False)
        self.OMQt.setGeometry(QtCore.QRect(220, 120, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OMQt.setFont(font)
        self.OMQt.setMinimum(-5)
        self.OMQt.setMaximum(5)
        self.OMQt.setProperty("value", 5)
        self.OMQt.setObjectName("OMQt")
        self.INT_lab_11 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_11.setEnabled(True)
        self.INT_lab_11.setGeometry(QtCore.QRect(280, 210, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_11.setFont(font)
        self.INT_lab_11.setObjectName("INT_lab_11")
        self.INT_lab_12 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_12.setEnabled(True)
        self.INT_lab_12.setGeometry(QtCore.QRect(300, 30, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_12.setFont(font)
        self.INT_lab_12.setObjectName("INT_lab_12")
        self.INT_lab_13 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_13.setEnabled(True)
        self.INT_lab_13.setGeometry(QtCore.QRect(190, 180, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_13.setFont(font)
        self.INT_lab_13.setObjectName("INT_lab_13")
        self.INT_lab_15 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_15.setEnabled(True)
        self.INT_lab_15.setGeometry(QtCore.QRect(190, 210, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_15.setFont(font)
        self.INT_lab_15.setObjectName("INT_lab_15")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(520, 0, 20, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.BluePrint_lab_2 = QtWidgets.QLabel(self.centralwidget)
        self.BluePrint_lab_2.setGeometry(QtCore.QRect(560, 0, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BluePrint_lab_2.setFont(font)
        self.BluePrint_lab_2.setObjectName("BluePrint_lab_2")
        self.PROFQt = QtWidgets.QCheckBox(self.centralwidget)
        self.PROFQt.setEnabled(False)
        self.PROFQt.setGeometry(QtCore.QRect(10, 220, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PROFQt.setFont(font)
        self.PROFQt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.PROFQt.setObjectName("PROFQt")
        self.KTYCQt = QtWidgets.QCheckBox(self.centralwidget)
        self.KTYCQt.setEnabled(True)
        self.KTYCQt.setGeometry(QtCore.QRect(190, 260, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.KTYCQt.setFont(font)
        self.KTYCQt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.KTYCQt.setObjectName("KTYCQt")
        self.TERPQt = QtWidgets.QCheckBox(self.centralwidget)
        self.TERPQt.setEnabled(False)
        self.TERPQt.setGeometry(QtCore.QRect(110, 120, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TERPQt.setFont(font)
        self.TERPQt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TERPQt.setObjectName("TERPQt")
        self.TMQt = QtWidgets.QCheckBox(self.centralwidget)
        self.TMQt.setEnabled(False)
        self.TMQt.setGeometry(QtCore.QRect(110, 90, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TMQt.setFont(font)
        self.TMQt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TMQt.setObjectName("TMQt")
        self.RRchQt = QtWidgets.QCheckBox(self.centralwidget)
        self.RRchQt.setEnabled(True)
        self.RRchQt.setGeometry(QtCore.QRect(110, 150, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RRchQt.setFont(font)
        self.RRchQt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.RRchQt.setObjectName("RRchQt")
        self.WPQt = QtWidgets.QSpinBox(self.centralwidget)
        self.WPQt.setGeometry(QtCore.QRect(610, 180, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WPQt.setFont(font)
        self.WPQt.setMaximum(0)
        self.WPQt.setProperty("value", 0)
        self.WPQt.setObjectName("WPQt")
        self.INT_lab_14 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_14.setGeometry(QtCore.QRect(570, 180, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.INT_lab_14.setFont(font)
        self.INT_lab_14.setObjectName("INT_lab_14")
        self.MQt = QtWidgets.QSpinBox(self.centralwidget)
        self.MQt.setGeometry(QtCore.QRect(630, 30, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MQt.setFont(font)
        self.MQt.setMinimum(1)
        self.MQt.setMaximum(5)
        self.MQt.setProperty("value", 4)
        self.MQt.setObjectName("MQt")
        self.INT_lab_16 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_16.setGeometry(QtCore.QRect(550, 30, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_16.setFont(font)
        self.INT_lab_16.setObjectName("INT_lab_16")
        self.ASScQt = QtWidgets.QSpinBox(self.centralwidget)
        self.ASScQt.setEnabled(False)
        self.ASScQt.setGeometry(QtCore.QRect(640, 110, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ASScQt.setFont(font)
        self.ASScQt.setMaximum(15)
        self.ASScQt.setObjectName("ASScQt")
        self.ASSQt = QtWidgets.QSpinBox(self.centralwidget)
        self.ASSQt.setEnabled(False)
        self.ASSQt.setGeometry(QtCore.QRect(640, 130, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ASSQt.setFont(font)
        self.ASSQt.setMaximum(10)
        self.ASSQt.setObjectName("ASSQt")
        self.INT_lab_18 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_18.setEnabled(True)
        self.INT_lab_18.setGeometry(QtCore.QRect(570, 130, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_18.setFont(font)
        self.INT_lab_18.setObjectName("INT_lab_18")
        self.INT_lab_19 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_19.setEnabled(True)
        self.INT_lab_19.setGeometry(QtCore.QRect(540, 110, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_19.setFont(font)
        self.INT_lab_19.setObjectName("INT_lab_19")
        self.INT_lab_10 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_10.setGeometry(QtCore.QRect(540, 290, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_10.setFont(font)
        self.INT_lab_10.setObjectName("INT_lab_10")
        self.INT_lab_17 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_17.setGeometry(QtCore.QRect(580, 260, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_17.setFont(font)
        self.INT_lab_17.setObjectName("INT_lab_17")
        self.INT_lab_23 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_23.setGeometry(QtCore.QRect(470, 310, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.INT_lab_23.setFont(font)
        self.INT_lab_23.setObjectName("INT_lab_23")
        self.QQt = QtWidgets.QComboBox(self.centralwidget)
        self.QQt.setEnabled(False)
        self.QQt.setGeometry(QtCore.QRect(350, 180, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QQt.setFont(font)
        self.QQt.setEditable(False)
        self.QQt.setObjectName("QQt")
        self.QQt.addItem("")
        self.QQt.addItem("")
        self.QQt.addItem("")
        self.QQt.addItem("")
        self.QQt.addItem("")
        self.CRnameQt = QtWidgets.QComboBox(self.centralwidget)
        self.CRnameQt.setGeometry(QtCore.QRect(10, 30, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CRnameQt.setFont(font)
        self.CRnameQt.setEditable(False)
        self.CRnameQt.setCurrentText("")
        self.CRnameQt.setObjectName("CRnameQt")
        self.BPnameQt = QtWidgets.QComboBox(self.centralwidget)
        self.BPnameQt.setGeometry(QtCore.QRect(320, 0, 211, 22))
        self.BPnameQt.setEditable(False)
        self.BPnameQt.setCurrentText("")
        self.BPnameQt.setObjectName("BPnameQt")
        self.PChQt = QtWidgets.QSpinBox(self.centralwidget)
        self.PChQt.setEnabled(False)
        self.PChQt.setGeometry(QtCore.QRect(390, 30, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PChQt.setFont(font)
        self.PChQt.setMinimum(-5)
        self.PChQt.setMaximum(5)
        self.PChQt.setObjectName("PChQt")
        self.OSQt = QtWidgets.QSpinBox(self.centralwidget)
        self.OSQt.setEnabled(False)
        self.OSQt.setGeometry(QtCore.QRect(220, 180, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OSQt.setFont(font)
        self.OSQt.setMaximum(5)
        self.OSQt.setObjectName("OSQt")
        self.NQt = QtWidgets.QSpinBox(self.centralwidget)
        self.NQt.setEnabled(False)
        self.NQt.setGeometry(QtCore.QRect(360, 210, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NQt.setFont(font)
        self.NQt.setMinimum(1)
        self.NQt.setMaximum(5)
        self.NQt.setObjectName("NQt")
        self.StartBtnQt = QtWidgets.QPushButton(self.centralwidget)
        self.StartBtnQt.setEnabled(True)
        self.StartBtnQt.setGeometry(QtCore.QRect(0, 0, 691, 371))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.StartBtnQt.setFont(font)
        self.StartBtnQt.setProperty("lol", False)
        self.StartBtnQt.setObjectName("StartBtnQt")
        self.Since_lab_2 = QtWidgets.QLabel(self.centralwidget)
        self.Since_lab_2.setEnabled(True)
        self.Since_lab_2.setGeometry(QtCore.QRect(10, 280, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Since_lab_2.setFont(font)
        self.Since_lab_2.setObjectName("Since_lab_2")
        self.MERITchQt = QtWidgets.QLineEdit(self.centralwidget)
        self.MERITchQt.setEnabled(False)
        self.MERITchQt.setGeometry(QtCore.QRect(10, 300, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MERITchQt.setFont(font)
        self.MERITchQt.setObjectName("MERITchQt")
        self.OMMChQt = QtWidgets.QSpinBox(self.centralwidget)
        self.OMMChQt.setEnabled(False)
        self.OMMChQt.setGeometry(QtCore.QRect(470, 110, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OMMChQt.setFont(font)
        self.OMMChQt.setMaximum(5)
        self.OMMChQt.setObjectName("OMMChQt")
        self.INT_lab_21 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_21.setEnabled(True)
        self.INT_lab_21.setGeometry(QtCore.QRect(420, 110, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_21.setFont(font)
        self.INT_lab_21.setObjectName("INT_lab_21")
        self.DebaffSTRQt = QtWidgets.QLabel(self.centralwidget)
        self.DebaffSTRQt.setGeometry(QtCore.QRect(210, 320, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DebaffSTRQt.setFont(font)
        self.DebaffSTRQt.setObjectName("DebaffSTRQt")
        self.DebaffOMMQt = QtWidgets.QLabel(self.centralwidget)
        self.DebaffOMMQt.setGeometry(QtCore.QRect(210, 340, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DebaffOMMQt.setFont(font)
        self.DebaffOMMQt.setObjectName("DebaffOMMQt")
        self.DebaffMRQt = QtWidgets.QLabel(self.centralwidget)
        self.DebaffMRQt.setGeometry(QtCore.QRect(420, 140, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DebaffMRQt.setFont(font)
        self.DebaffMRQt.setObjectName("DebaffMRQt")
        self.TChQt = QtWidgets.QSpinBox(self.centralwidget)
        self.TChQt.setEnabled(False)
        self.TChQt.setGeometry(QtCore.QRect(400, 70, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TChQt.setFont(font)
        self.TChQt.setMaximum(0)
        self.TChQt.setObjectName("TChQt")
        self.TQt = QtWidgets.QSpinBox(self.centralwidget)
        self.TQt.setEnabled(False)
        self.TQt.setGeometry(QtCore.QRect(250, 70, 21, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TQt.setFont(font)
        self.TQt.setFrame(True)
        self.TQt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.TQt.setMinimum(0)
        self.TQt.setMaximum(10)
        self.TQt.setProperty("value", 0)
        self.TQt.setObjectName("TQt")
        self.NZQt = QtWidgets.QSpinBox(self.centralwidget)
        self.NZQt.setEnabled(False)
        self.NZQt.setGeometry(QtCore.QRect(260, 30, 21, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NZQt.setFont(font)
        self.NZQt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NZQt.setWrapping(False)
        self.NZQt.setFrame(True)
        self.NZQt.setReadOnly(False)
        self.NZQt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.NZQt.setMinimum(0)
        self.NZQt.setMaximum(10)
        self.NZQt.setProperty("value", 0)
        self.NZQt.setObjectName("NZQt")
        self.PQt = QtWidgets.QSpinBox(self.centralwidget)
        self.PQt.setEnabled(False)
        self.PQt.setGeometry(QtCore.QRect(320, 30, 21, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PQt.setFont(font)
        self.PQt.setFrame(True)
        self.PQt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.PQt.setKeyboardTracking(True)
        self.PQt.setProperty("showGroupSeparator", False)
        self.PQt.setMinimum(0)
        self.PQt.setMaximum(10)
        self.PQt.setProperty("value", 0)
        self.PQt.setObjectName("PQt")
        self.INT_lab_22 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_22.setEnabled(True)
        self.INT_lab_22.setGeometry(QtCore.QRect(350, 30, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_22.setFont(font)
        self.INT_lab_22.setObjectName("INT_lab_22")
        self.INT_lab_24 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_24.setEnabled(True)
        self.INT_lab_24.setGeometry(QtCore.QRect(360, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_24.setFont(font)
        self.INT_lab_24.setObjectName("INT_lab_24")
        self.NumRollQt = QtWidgets.QSpinBox(self.centralwidget)
        self.NumRollQt.setEnabled(False)
        self.NumRollQt.setGeometry(QtCore.QRect(640, 290, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NumRollQt.setFont(font)
        self.NumRollQt.setFrame(True)
        self.NumRollQt.setAlignment(QtCore.Qt.AlignCenter)
        self.NumRollQt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.NumRollQt.setKeyboardTracking(True)
        self.NumRollQt.setProperty("showGroupSeparator", False)
        self.NumRollQt.setMinimum(0)
        self.NumRollQt.setMaximum(50)
        self.NumRollQt.setProperty("value", 0)
        self.NumRollQt.setObjectName("NumRollQt")
        self.DicePullQt = QtWidgets.QSpinBox(self.centralwidget)
        self.DicePullQt.setEnabled(False)
        self.DicePullQt.setGeometry(QtCore.QRect(640, 260, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DicePullQt.setFont(font)
        self.DicePullQt.setFrame(True)
        self.DicePullQt.setAlignment(QtCore.Qt.AlignCenter)
        self.DicePullQt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.DicePullQt.setKeyboardTracking(True)
        self.DicePullQt.setProperty("showGroupSeparator", False)
        self.DicePullQt.setMinimum(0)
        self.DicePullQt.setMaximum(50)
        self.DicePullQt.setProperty("value", 0)
        self.DicePullQt.setObjectName("DicePullQt")
        self.KolTYQt = QtWidgets.QSpinBox(self.centralwidget)
        self.KolTYQt.setEnabled(False)
        self.KolTYQt.setGeometry(QtCore.QRect(190, 230, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.KolTYQt.setFont(font)
        self.KolTYQt.setFrame(True)
        self.KolTYQt.setAlignment(QtCore.Qt.AlignCenter)
        self.KolTYQt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.KolTYQt.setKeyboardTracking(True)
        self.KolTYQt.setProperty("showGroupSeparator", False)
        self.KolTYQt.setMinimum(0)
        self.KolTYQt.setMaximum(999)
        self.KolTYQt.setProperty("value", 0)
        self.KolTYQt.setObjectName("KolTYQt")
        self.PCRFTQt = QtWidgets.QCheckBox(self.centralwidget)
        self.PCRFTQt.setEnabled(False)
        self.PCRFTQt.setGeometry(QtCore.QRect(80, 220, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PCRFTQt.setFont(font)
        self.PCRFTQt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PCRFTQt.setObjectName("PCRFTQt")
        self.PSINCQt = QtWidgets.QCheckBox(self.centralwidget)
        self.PSINCQt.setEnabled(False)
        self.PSINCQt.setGeometry(QtCore.QRect(80, 240, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PSINCQt.setFont(font)
        self.PSINCQt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PSINCQt.setObjectName("PSINCQt")
        self.PCOMPQt = QtWidgets.QCheckBox(self.centralwidget)
        self.PCOMPQt.setEnabled(False)
        self.PCOMPQt.setGeometry(QtCore.QRect(80, 260, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PCOMPQt.setFont(font)
        self.PCOMPQt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PCOMPQt.setObjectName("PCOMPQt")
        self.MERITQt = QtWidgets.QSpinBox(self.centralwidget)
        self.MERITQt.setEnabled(False)
        self.MERITQt.setGeometry(QtCore.QRect(90, 300, 31, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MERITQt.setFont(font)
        self.MERITQt.setFrame(True)
        self.MERITQt.setAlignment(QtCore.Qt.AlignCenter)
        self.MERITQt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.MERITQt.setKeyboardTracking(True)
        self.MERITQt.setProperty("showGroupSeparator", False)
        self.MERITQt.setMinimum(0)
        self.MERITQt.setMaximum(999)
        self.MERITQt.setProperty("value", 0)
        self.MERITQt.setObjectName("MERITQt")
        self.OYQt = QtWidgets.QSpinBox(self.centralwidget)
        self.OYQt.setEnabled(False)
        self.OYQt.setGeometry(QtCore.QRect(460, 330, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.OYQt.setFont(font)
        self.OYQt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OYQt.setFrame(False)
        self.OYQt.setAlignment(QtCore.Qt.AlignCenter)
        self.OYQt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.OYQt.setKeyboardTracking(True)
        self.OYQt.setProperty("showGroupSeparator", False)
        self.OYQt.setMinimum(-50)
        self.OYQt.setMaximum(50)
        self.OYQt.setProperty("value", 0)
        self.OYQt.setObjectName("OYQt")
        self.WP3Qt = QtWidgets.QRadioButton(self.centralwidget)
        self.WP3Qt.setEnabled(False)
        self.WP3Qt.setGeometry(QtCore.QRect(570, 210, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.WP3Qt.setFont(font)
        self.WP3Qt.setChecked(True)
        self.WP3Qt.setObjectName("WP3Qt")
        self.RRQt = QtWidgets.QRadioButton(self.centralwidget)
        self.RRQt.setEnabled(False)
        self.RRQt.setGeometry(QtCore.QRect(620, 210, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RRQt.setFont(font)
        self.RRQt.setObjectName("RRQt")
        self.DebaffCRFTQt = QtWidgets.QLabel(self.centralwidget)
        self.DebaffCRFTQt.setGeometry(QtCore.QRect(540, 320, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DebaffCRFTQt.setFont(font)
        self.DebaffCRFTQt.setObjectName("DebaffCRFTQt")
        self.DebaffMQt = QtWidgets.QLabel(self.centralwidget)
        self.DebaffMQt.setGeometry(QtCore.QRect(560, 340, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DebaffMQt.setFont(font)
        self.DebaffMQt.setObjectName("DebaffMQt")
        self.CRsaveBTNQt = QtWidgets.QPushButton(self.centralwidget)
        self.CRsaveBTNQt.setEnabled(True)
        self.CRsaveBTNQt.setGeometry(QtCore.QRect(90, 50, 71, 21))
        self.CRsaveBTNQt.setObjectName("CRsaveBTNQt")
        self.BPsaveBTNQt = QtWidgets.QPushButton(self.centralwidget)
        self.BPsaveBTNQt.setEnabled(True)
        self.BPsaveBTNQt.setGeometry(QtCore.QRect(460, 40, 71, 21))
        self.BPsaveBTNQt.setObjectName("BPsaveBTNQt")
        self.CRsaveQt = QtWidgets.QLineEdit(self.centralwidget)
        self.CRsaveQt.setGeometry(QtCore.QRect(10, 50, 81, 20))
        self.CRsaveQt.setObjectName("CRsaveQt")
        self.BPsaveQt = QtWidgets.QLineEdit(self.centralwidget)
        self.BPsaveQt.setGeometry(QtCore.QRect(440, 20, 91, 20))
        self.BPsaveQt.setObjectName("BPsaveQt")
        self.DebaffOYQt = QtWidgets.QLabel(self.centralwidget)
        self.DebaffOYQt.setGeometry(QtCore.QRect(210, 290, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DebaffOYQt.setFont(font)
        self.DebaffOYQt.setObjectName("DebaffOYQt")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(290, 20, 151, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(290, 50, 151, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setEnabled(False)
        self.line_7.setGeometry(QtCore.QRect(280, 30, 20, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_7.setFont(font)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setEnabled(False)
        self.line_8.setGeometry(QtCore.QRect(430, 30, 20, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setEnabled(True)
        self.line_9.setGeometry(QtCore.QRect(230, 60, 221, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(230, 90, 291, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setEnabled(False)
        self.line_11.setGeometry(QtCore.QRect(440, 70, 20, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_11.setFont(font)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setEnabled(False)
        self.line_12.setGeometry(QtCore.QRect(220, 70, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_12.setFont(font)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(270, 160, 251, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setEnabled(False)
        self.line_15.setGeometry(QtCore.QRect(260, 100, 20, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_15.setFont(font)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setEnabled(False)
        self.line_16.setGeometry(QtCore.QRect(510, 100, 20, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_16.setFont(font)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(320, 110, 16, 20))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(320, 140, 16, 20))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.BuffPROFQt = QtWidgets.QLabel(self.centralwidget)
        self.BuffPROFQt.setGeometry(QtCore.QRect(30, 330, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BuffPROFQt.setFont(font)
        self.BuffPROFQt.setObjectName("BuffPROFQt")
        self.ASSchQt = QtWidgets.QCheckBox(self.centralwidget)
        self.ASSchQt.setEnabled(True)
        self.ASSchQt.setGeometry(QtCore.QRect(580, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ASSchQt.setFont(font)
        self.ASSchQt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ASSchQt.setObjectName("ASSchQt")
        self.ASSnameQt = QtWidgets.QComboBox(self.centralwidget)
        self.ASSnameQt.setEnabled(False)
        self.ASSnameQt.setGeometry(QtCore.QRect(550, 90, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ASSnameQt.setFont(font)
        self.ASSnameQt.setEditable(False)
        self.ASSnameQt.setCurrentText("")
        self.ASSnameQt.setObjectName("ASSnameQt")
        self.DebaffASSQt = QtWidgets.QLabel(self.centralwidget)
        self.DebaffASSQt.setGeometry(QtCore.QRect(580, 150, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DebaffASSQt.setFont(font)
        self.DebaffASSQt.setObjectName("DebaffASSQt")
        self.SQt = QtWidgets.QSpinBox(self.centralwidget)
        self.SQt.setEnabled(False)
        self.SQt.setGeometry(QtCore.QRect(490, 70, 21, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SQt.setFont(font)
        self.SQt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SQt.setWrapping(False)
        self.SQt.setFrame(True)
        self.SQt.setReadOnly(False)
        self.SQt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SQt.setMinimum(0)
        self.SQt.setMaximum(10)
        self.SQt.setProperty("value", 0)
        self.SQt.setObjectName("SQt")
        self.INT_lab_20 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_20.setEnabled(True)
        self.INT_lab_20.setGeometry(QtCore.QRect(470, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_20.setFont(font)
        self.INT_lab_20.setObjectName("INT_lab_20")
        self.DMQt = QtWidgets.QSpinBox(self.centralwidget)
        self.DMQt.setEnabled(False)
        self.DMQt.setGeometry(QtCore.QRect(360, 240, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DMQt.setFont(font)
        self.DMQt.setMinimum(0)
        self.DMQt.setMaximum(5)
        self.DMQt.setProperty("value", 0)
        self.DMQt.setObjectName("DMQt")
        self.INT_lab_25 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_25.setEnabled(True)
        self.INT_lab_25.setGeometry(QtCore.QRect(320, 240, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.INT_lab_25.setFont(font)
        self.INT_lab_25.setObjectName("INT_lab_25")
        self.Random_lab = QtWidgets.QLabel(self.centralwidget)
        self.Random_lab.setGeometry(QtCore.QRect(280, 370, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Random_lab.setFont(font)
        self.Random_lab.setObjectName("Random_lab")
        self.DebaffWPQt = QtWidgets.QLabel(self.centralwidget)
        self.DebaffWPQt.setGeometry(QtCore.QRect(570, 230, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DebaffWPQt.setFont(font)
        self.DebaffWPQt.setObjectName("DebaffWPQt")
        self.KQt = QtWidgets.QSpinBox(self.centralwidget)
        self.KQt.setEnabled(False)
        self.KQt.setGeometry(QtCore.QRect(20, 400, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.KQt.setFont(font)
        self.KQt.setMinimum(1)
        self.KQt.setMaximum(10000)
        self.KQt.setObjectName("KQt")
        self.INT_lab_26 = QtWidgets.QLabel(self.centralwidget)
        self.INT_lab_26.setEnabled(True)
        self.INT_lab_26.setGeometry(QtCore.QRect(10, 380, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.INT_lab_26.setFont(font)
        self.INT_lab_26.setToolTip("")
        self.INT_lab_26.setObjectName("INT_lab_26")
        self.RunQt = QtWidgets.QPushButton(self.centralwidget)
        self.RunQt.setEnabled(False)
        self.RunQt.setGeometry(QtCore.QRect(10, 430, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RunQt.setFont(font)
        self.RunQt.setObjectName("RunQt")
        self.DetTextQt = QtWidgets.QTextEdit(self.centralwidget)
        self.DetTextQt.setGeometry(QtCore.QRect(103, 400, 581, 421))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DetTextQt.setFont(font)
        self.DetTextQt.setObjectName("DetTextQt")
        self.NAQt = QtWidgets.QCheckBox(self.centralwidget)
        self.NAQt.setEnabled(False)
        self.NAQt.setGeometry(QtCore.QRect(270, 100, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NAQt.setFont(font)
        self.NAQt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.NAQt.setObjectName("NAQt")
        self.OtherQt = QtWidgets.QSpinBox(self.centralwidget)
        self.OtherQt.setEnabled(True)
        self.OtherQt.setGeometry(QtCore.QRect(120, 200, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OtherQt.setFont(font)
        self.OtherQt.setMinimum(-5)
        self.OtherQt.setMaximum(5)
        self.OtherQt.setObjectName("OtherQt")
        self.Computer_lab_2 = QtWidgets.QLabel(self.centralwidget)
        self.Computer_lab_2.setEnabled(True)
        self.Computer_lab_2.setGeometry(QtCore.QRect(110, 180, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Computer_lab_2.setFont(font)
        self.Computer_lab_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Computer_lab_2.setObjectName("Computer_lab_2")
        self.line.raise_()
        self.line_2.raise_()
        self.Crafter_lab.raise_()
        self.BluePrint_lab.raise_()
        self.INTQt.raise_()
        self.CRFTQt.raise_()
        self.SINCQt.raise_()
        self.INT_lab.raise_()
        self.Craft_lab.raise_()
        self.Since_lab.raise_()
        self.Computer_lab.raise_()
        self.COMPQt.raise_()
        self.TYQt.raise_()
        self.INT_lab_2.raise_()
        self.RQt.raise_()
        self.INT_lab_3.raise_()
        self.STRQt.raise_()
        self.INT_lab_4.raise_()
        self.OMMQt.raise_()
        self.INT_lab_5.raise_()
        self.OMRQt.raise_()
        self.INT_lab_6.raise_()
        self.line_3.raise_()
        self.INT_lab_7.raise_()
        self.INT_lab_8.raise_()
        self.INT_lab_9.raise_()
        self.OM.raise_()
        self.OMQt.raise_()
        self.INT_lab_11.raise_()
        self.INT_lab_12.raise_()
        self.INT_lab_13.raise_()
        self.INT_lab_15.raise_()
        self.line_4.raise_()
        self.BluePrint_lab_2.raise_()
        self.PROFQt.raise_()
        self.KTYCQt.raise_()
        self.TERPQt.raise_()
        self.TMQt.raise_()
        self.RRchQt.raise_()
        self.WPQt.raise_()
        self.INT_lab_14.raise_()
        self.MQt.raise_()
        self.INT_lab_16.raise_()
        self.ASScQt.raise_()
        self.ASSQt.raise_()
        self.INT_lab_18.raise_()
        self.INT_lab_19.raise_()
        self.INT_lab_10.raise_()
        self.INT_lab_17.raise_()
        self.INT_lab_23.raise_()
        self.QQt.raise_()
        self.CRnameQt.raise_()
        self.BPnameQt.raise_()
        self.PChQt.raise_()
        self.OSQt.raise_()
        self.NQt.raise_()
        self.Since_lab_2.raise_()
        self.MERITchQt.raise_()
        self.OMMChQt.raise_()
        self.INT_lab_21.raise_()
        self.DebaffSTRQt.raise_()
        self.DebaffOMMQt.raise_()
        self.DebaffMRQt.raise_()
        self.TChQt.raise_()
        self.TQt.raise_()
        self.NZQt.raise_()
        self.PQt.raise_()
        self.INT_lab_22.raise_()
        self.INT_lab_24.raise_()
        self.NumRollQt.raise_()
        self.DicePullQt.raise_()
        self.KolTYQt.raise_()
        self.PCRFTQt.raise_()
        self.PSINCQt.raise_()
        self.PCOMPQt.raise_()
        self.MERITQt.raise_()
        self.OYQt.raise_()
        self.WP3Qt.raise_()
        self.RRQt.raise_()
        self.DebaffCRFTQt.raise_()
        self.DebaffMQt.raise_()
        self.CRsaveBTNQt.raise_()
        self.BPsaveBTNQt.raise_()
        self.CRsaveQt.raise_()
        self.BPsaveQt.raise_()
        self.DebaffOYQt.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.line_9.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        self.line_12.raise_()
        self.line_14.raise_()
        self.line_15.raise_()
        self.line_16.raise_()
        self.line_17.raise_()
        self.line_18.raise_()
        self.BuffPROFQt.raise_()
        self.ASSchQt.raise_()
        self.ASSnameQt.raise_()
        self.DebaffASSQt.raise_()
        self.SQt.raise_()
        self.INT_lab_20.raise_()
        self.DMQt.raise_()
        self.INT_lab_25.raise_()
        self.Random_lab.raise_()
        self.DebaffWPQt.raise_()
        self.KQt.raise_()
        self.INT_lab_26.raise_()
        self.RunQt.raise_()
        self.DetTextQt.raise_()
        self.NAQt.raise_()
        self.OtherQt.raise_()
        self.Computer_lab_2.raise_()
        self.StartBtnQt.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.QQt.setCurrentIndex(2)
        self.CRnameQt.setCurrentIndex(-1)
        self.ASSnameQt.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.CRsaveBTNQt, self.INTQt)
        MainWindow.setTabOrder(self.INTQt, self.CRFTQt)
        MainWindow.setTabOrder(self.CRFTQt, self.SINCQt)
        MainWindow.setTabOrder(self.SINCQt, self.COMPQt)
        MainWindow.setTabOrder(self.COMPQt, self.RRchQt)
        MainWindow.setTabOrder(self.RRchQt, self.TMQt)
        MainWindow.setTabOrder(self.TMQt, self.TERPQt)
        MainWindow.setTabOrder(self.TERPQt, self.PROFQt)
        MainWindow.setTabOrder(self.PROFQt, self.PCRFTQt)
        MainWindow.setTabOrder(self.PCRFTQt, self.PSINCQt)
        MainWindow.setTabOrder(self.PSINCQt, self.PCOMPQt)
        MainWindow.setTabOrder(self.PCOMPQt, self.BPnameQt)
        MainWindow.setTabOrder(self.BPnameQt, self.TYQt)
        MainWindow.setTabOrder(self.TYQt, self.RQt)
        MainWindow.setTabOrder(self.RQt, self.PChQt)
        MainWindow.setTabOrder(self.PChQt, self.TChQt)
        MainWindow.setTabOrder(self.TChQt, self.OMQt)
        MainWindow.setTabOrder(self.OMQt, self.OMMQt)
        MainWindow.setTabOrder(self.OMMQt, self.OMRQt)
        MainWindow.setTabOrder(self.OMRQt, self.OMMChQt)
        MainWindow.setTabOrder(self.OMMChQt, self.OSQt)
        MainWindow.setTabOrder(self.OSQt, self.QQt)
        MainWindow.setTabOrder(self.QQt, self.NQt)
        MainWindow.setTabOrder(self.NQt, self.MQt)
        MainWindow.setTabOrder(self.MQt, self.ASSQt)
        MainWindow.setTabOrder(self.ASSQt, self.ASScQt)
        MainWindow.setTabOrder(self.ASScQt, self.WPQt)
        MainWindow.setTabOrder(self.WPQt, self.WP3Qt)
        MainWindow.setTabOrder(self.WP3Qt, self.RRQt)
        MainWindow.setTabOrder(self.RRQt, self.NZQt)
        MainWindow.setTabOrder(self.NZQt, self.PQt)
        MainWindow.setTabOrder(self.PQt, self.NumRollQt)
        MainWindow.setTabOrder(self.NumRollQt, self.DicePullQt)
        MainWindow.setTabOrder(self.DicePullQt, self.KolTYQt)
        MainWindow.setTabOrder(self.KolTYQt, self.MERITchQt)
        MainWindow.setTabOrder(self.MERITchQt, self.KTYCQt)
        MainWindow.setTabOrder(self.KTYCQt, self.StartBtnQt)
        MainWindow.setTabOrder(self.StartBtnQt, self.MERITQt)
        MainWindow.setTabOrder(self.MERITQt, self.OYQt)
        MainWindow.setTabOrder(self.OYQt, self.CRnameQt)
        MainWindow.setTabOrder(self.CRnameQt, self.TQt)
        MainWindow.setTabOrder(self.TQt, self.STRQt)
        MainWindow.setTabOrder(self.STRQt, self.BPsaveBTNQt)
        MainWindow.setTabOrder(self.BPsaveBTNQt, self.CRsaveQt)
        MainWindow.setTabOrder(self.CRsaveQt, self.BPsaveQt)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Crafter_lab.setText(_translate("MainWindow", "Мастер"))
        self.BluePrint_lab.setText(_translate("MainWindow", "Чертеж"))
        self.INTQt.setToolTip(_translate("MainWindow", "Интеллект"))
        self.CRFTQt.setToolTip(_translate("MainWindow", "Ремесло"))
        self.SINCQt.setToolTip(_translate("MainWindow", "Точные Науки"))
        self.INT_lab.setToolTip(_translate("MainWindow", "Интеллект"))
        self.INT_lab.setText(_translate("MainWindow", "INT"))
        self.Craft_lab.setToolTip(_translate("MainWindow", "Ремесло"))
        self.Craft_lab.setText(_translate("MainWindow", "Craft"))
        self.Since_lab.setToolTip(_translate("MainWindow", "Точные Науки"))
        self.Since_lab.setText(_translate("MainWindow", "Since"))
        self.Computer_lab.setToolTip(_translate("MainWindow", "Компьютеры"))
        self.Computer_lab.setText(_translate("MainWindow", "Computer"))
        self.COMPQt.setToolTip(_translate("MainWindow", "Компьютеры"))
        self.TYQt.setToolTip(_translate("MainWindow", "ТУ"))
        self.INT_lab_2.setToolTip(_translate("MainWindow", "ТУ"))
        self.INT_lab_2.setText(_translate("MainWindow", "TY"))
        self.RQt.setToolTip(_translate("MainWindow", "Физический размер предмета варьируется от 1 до  бесконечности"))
        self.INT_lab_3.setText(_translate("MainWindow", "Размер"))
        self.STRQt.setToolTip(_translate("MainWindow", "Атрибут для Требования"))
        self.INT_lab_4.setToolTip(_translate("MainWindow", "Атрибут для Требования"))
        self.INT_lab_4.setText(_translate("MainWindow", "ATT"))
        self.OMMQt.setToolTip(_translate("MainWindow", "ОМ для Ближнего Боя"))
        self.INT_lab_5.setToolTip(_translate("MainWindow", "ОМ для Ближнего Боя"))
        self.INT_lab_5.setText(_translate("MainWindow", "OMM"))
        self.OMRQt.setToolTip(_translate("MainWindow", "ОМ для Дальнего Боя"))
        self.INT_lab_6.setToolTip(_translate("MainWindow", "ОМ для Дальнего Боя"))
        self.INT_lab_6.setText(_translate("MainWindow", "OMR"))
        self.INT_lab_7.setToolTip(_translate("MainWindow", "Наименьшее Зачение (ТУ или Р)"))
        self.INT_lab_7.setText(_translate("MainWindow", "НЗ"))
        self.INT_lab_8.setToolTip(_translate("MainWindow", "Качество предмета определяет то, какие значения добрасываются"))
        self.INT_lab_8.setText(_translate("MainWindow", "Качество"))
        self.INT_lab_9.setText(_translate("MainWindow", "T"))
        self.OM.setToolTip(_translate("MainWindow", "Основной модификатор (броня)"))
        self.OM.setText(_translate("MainWindow", "OM"))
        self.OMQt.setToolTip(_translate("MainWindow", "Основной модификатор"))
        self.INT_lab_11.setToolTip(_translate("MainWindow", "Назначения"))
        self.INT_lab_11.setText(_translate("MainWindow", "Назначения"))
        self.INT_lab_12.setToolTip(_translate("MainWindow", "Прочность"))
        self.INT_lab_12.setText(_translate("MainWindow", "П"))
        self.INT_lab_13.setToolTip(_translate("MainWindow", "В этом пункте учитываются все уникальные параметры предмета (не описываются ОМ, ДМ и К)"))
        self.INT_lab_13.setText(_translate("MainWindow", "ОС"))
        self.INT_lab_15.setToolTip(_translate("MainWindow", "Кол-во необходимых деталей"))
        self.INT_lab_15.setText(_translate("MainWindow", "Детали"))
        self.BluePrint_lab_2.setText(_translate("MainWindow", "Остальное"))
        self.PROFQt.setToolTip(_translate("MainWindow", "Профессия"))
        self.PROFQt.setText(_translate("MainWindow", "Проф"))
        self.KTYCQt.setToolTip(_translate("MainWindow", "Есть ли больше половины деталей большего ТУ?"))
        self.KTYCQt.setText(_translate("MainWindow", "KTYC"))
        self.TERPQt.setToolTip(_translate("MainWindow", "Терпение"))
        self.TERPQt.setText(_translate("MainWindow", "Терп."))
        self.TMQt.setToolTip(_translate("MainWindow", "Тайм-Менеджмент"))
        self.TMQt.setText(_translate("MainWindow", "TM"))
        self.RRchQt.setToolTip(_translate("MainWindow", "Есть ли подходящая Черта? (Технарь, Айтишник, Золотые Руки)"))
        self.RRchQt.setText(_translate("MainWindow", "RR"))
        self.WPQt.setToolTip(_translate("MainWindow", "Сколько ПСВ тратишь?"))
        self.INT_lab_14.setToolTip(_translate("MainWindow", "Пункты Силы Воли"))
        self.INT_lab_14.setText(_translate("MainWindow", "ПСВ"))
        self.MQt.setToolTip(_translate("MainWindow", "Уровень Мастерской"))
        self.INT_lab_16.setToolTip(_translate("MainWindow", "Уровень Мастерской"))
        self.INT_lab_16.setText(_translate("MainWindow", "Мастерская"))
        self.ASScQt.setToolTip(_translate("MainWindow", "Какой запас бросков у Ассистера (ИНТ+Навык + Терп)"))
        self.ASSQt.setToolTip(_translate("MainWindow", "Сколько в среднем Успехов на броске (проверить можно запустив Ассистера основным Крафтером)"))
        self.INT_lab_18.setToolTip(_translate("MainWindow", "Сколько в среднем Успехов на броске (проверить можно запустив Ассистера основным Крафтером)"))
        self.INT_lab_18.setText(_translate("MainWindow", "~  успехов"))
        self.INT_lab_19.setToolTip(_translate("MainWindow", "Какой запас бросков у Ассистера (ИНТ+Навык + Терп)"))
        self.INT_lab_19.setText(_translate("MainWindow", "Кол-во бросков"))
        self.INT_lab_10.setText(_translate("MainWindow", "Кол-во бросков"))
        self.INT_lab_17.setText(_translate("MainWindow", "Кубы:"))
        self.INT_lab_23.setToolTip(_translate("MainWindow", "Очки Улучшения"))
        self.INT_lab_23.setText(_translate("MainWindow", "OY"))
        self.QQt.setToolTip(_translate("MainWindow", "Качество предмета определяет то, какие значения добрасываются"))
        self.QQt.setCurrentText(_translate("MainWindow", "0: Обычное"))
        self.QQt.setItemText(0, _translate("MainWindow", "+2: Отличное"))
        self.QQt.setItemText(1, _translate("MainWindow", "+1: Хорошее"))
        self.QQt.setItemText(2, _translate("MainWindow", "0: Обычное"))
        self.QQt.setItemText(3, _translate("MainWindow", "-1: Плохое"))
        self.QQt.setItemText(4, _translate("MainWindow", "-2: Ужасное"))
        self.CRnameQt.setToolTip(_translate("MainWindow", "Выбери готового крафтера или создай нового"))
        self.BPnameQt.setToolTip(_translate("MainWindow", "Выбери готовый чертеж или создай новый"))
        self.PChQt.setToolTip(_translate("MainWindow", "Измените прочность"))
        self.OSQt.setToolTip(_translate("MainWindow", "В этом пункте учитываются все уникальные параметры предмета (не описываются ОМ, ДМ и К)"))
        self.NQt.setToolTip(_translate("MainWindow", "Назначения"))
        self.StartBtnQt.setStatusTip(_translate("MainWindow", "Жми, ёпта..."))
        self.StartBtnQt.setText(_translate("MainWindow", "Start Button"))
        self.Since_lab_2.setToolTip(_translate("MainWindow", "Навык, выбранный от уровня ТУ"))
        self.Since_lab_2.setText(_translate("MainWindow", "Выбранный Навык"))
        self.MERITchQt.setToolTip(_translate("MainWindow", "Навык, выбранный от уровня ТУ"))
        self.MERITchQt.setText(_translate("MainWindow", "Выбери TY"))
        self.OMMChQt.setToolTip(_translate("MainWindow", "Снятие штрафа за ОМ Ближнего Боя"))
        self.INT_lab_21.setToolTip(_translate("MainWindow", "Снятие штрафа за ОМ Ближнего Боя"))
        self.INT_lab_21.setText(_translate("MainWindow", "OMM T"))
        self.DebaffSTRQt.setToolTip(_translate("MainWindow", "Штрафы по Инициативе, Защите, Скорости и т.д. (штраф можно снять понижением Требований)"))
        self.DebaffSTRQt.setText(_translate("MainWindow", "Атрибут < Требований => Штрафы"))
        self.DebaffOMMQt.setToolTip(_translate("MainWindow", "Штрафы по Инициативе, Защите, Скорости и т.д. (штраф можно снять OMM T)"))
        self.DebaffOMMQt.setText(_translate("MainWindow", "Защита Ближнего Боя > 0 => Штрафы"))
        self.DebaffMRQt.setToolTip(_translate("MainWindow", "Сумма OMM + OMR = OM"))
        self.DebaffMRQt.setText(_translate("MainWindow", "OMM+OMR != OM"))
        self.TChQt.setToolTip(_translate("MainWindow", "Уравнивание Требований и Атрибута"))
        self.NZQt.setToolTip(_translate("MainWindow", "Наименьшее Зачение (ТУ или Р)"))
        self.PQt.setToolTip(_translate("MainWindow", "Прочность"))
        self.INT_lab_22.setToolTip(_translate("MainWindow", "Измените прочность"))
        self.INT_lab_22.setText(_translate("MainWindow", "П +/-"))
        self.INT_lab_24.setToolTip(_translate("MainWindow", "Уравнивание Требований и Атрибута"))
        self.INT_lab_24.setText(_translate("MainWindow", "Т +/-"))
        self.KolTYQt.setToolTip(_translate("MainWindow", "Кол-во необходимых деталей"))
        self.PCRFTQt.setToolTip(_translate("MainWindow", "Профессиональный навык Ремесло"))
        self.PCRFTQt.setText(_translate("MainWindow", "CRFT"))
        self.PSINCQt.setToolTip(_translate("MainWindow", "Профессиональный навык Точные Науки"))
        self.PSINCQt.setText(_translate("MainWindow", "SINC"))
        self.PCOMPQt.setToolTip(_translate("MainWindow", "Профессиональный навык Компьютеры"))
        self.PCOMPQt.setText(_translate("MainWindow", "COMP"))
        self.MERITQt.setToolTip(_translate("MainWindow", "Уровень навыка подходящего ТУ"))
        self.OYQt.setToolTip(_translate("MainWindow", "Очки Улучшения"))
        self.WP3Qt.setToolTip(_translate("MainWindow", "+3 куба к броску"))
        self.WP3Qt.setText(_translate("MainWindow", "+3"))
        self.RRQt.setToolTip(_translate("MainWindow", "Переброс неудачных кубов"))
        self.RRQt.setText(_translate("MainWindow", "RR"))
        self.DebaffCRFTQt.setToolTip(_translate("MainWindow", "Уровень Ремесла ниже уровня ТУ => вычитаются Успехи из каждого броска"))
        self.DebaffCRFTQt.setText(_translate("MainWindow", "CRFT < TY => - успехи"))
        self.DebaffMQt.setToolTip(_translate("MainWindow", "Уровень Мастерской ниже уровня ТУ => вычитаются Успехи из каждого броска"))
        self.DebaffMQt.setText(_translate("MainWindow", "М < TY => - успехи"))
        self.CRsaveBTNQt.setText(_translate("MainWindow", "Сохранить?"))
        self.BPsaveBTNQt.setText(_translate("MainWindow", "Сохранить?"))
        self.DebaffOYQt.setToolTip(_translate("MainWindow", "Чертеж действителен только при OY > 0"))
        self.DebaffOYQt.setText(_translate("MainWindow", ">>> OY должно быть больше 0 <<<"))
        self.BuffPROFQt.setToolTip(_translate("MainWindow", "Кроме \"снова 0\" еще \"снова 9\" за Профу"))
        self.BuffPROFQt.setText(_translate("MainWindow", "Доброс 9+"))
        self.ASSchQt.setToolTip(_translate("MainWindow", "Есть ли у вас Ассистеры?"))
        self.ASSchQt.setText(_translate("MainWindow", "Ассист"))
        self.ASSnameQt.setToolTip(_translate("MainWindow", "Выбери готового Ассистера из списка Крафтеров или установи вручную"))
        self.DebaffASSQt.setToolTip(_translate("MainWindow", "Количество бросков у Ассистера меньше, чем у Крафтера => до конца не поможет"))
        self.DebaffASSQt.setText(_translate("MainWindow", "Asst < Crafter"))
        self.SQt.setToolTip(_translate("MainWindow", "Структура (П+Р)"))
        self.INT_lab_20.setToolTip(_translate("MainWindow", "Структура (П+Р)"))
        self.INT_lab_20.setText(_translate("MainWindow", "С"))
        self.DMQt.setToolTip(_translate("MainWindow", "Дополнительный модификатор"))
        self.INT_lab_25.setToolTip(_translate("MainWindow", "Дополнительный модификатор"))
        self.INT_lab_25.setText(_translate("MainWindow", "ДМ"))
        self.Random_lab.setText(_translate("MainWindow", "Рендомайзер"))
        self.DebaffWPQt.setToolTip(_translate("MainWindow", "Кол-во потраченного ПСВ меньше общего кол-ва бросков"))
        self.DebaffWPQt.setText(_translate("MainWindow", "WP < NumRoll"))
        self.KQt.setToolTip(_translate("MainWindow", "Кол-во повторений"))
        self.INT_lab_26.setText(_translate("MainWindow", "Повторений"))
        self.RunQt.setText(_translate("MainWindow", "Погнали?"))
        self.NAQt.setToolTip(_translate("MainWindow", "Есть ли больше половины деталей большего ТУ?"))
        self.NAQt.setText(_translate("MainWindow", "Броня"))
        self.OtherQt.setToolTip(_translate("MainWindow", "(Спеца, Бонусы, и т.д.)"))
        self.Computer_lab_2.setToolTip(_translate("MainWindow", "(Спеца, Бонусы, и т.д.)"))
        self.Computer_lab_2.setText(_translate("MainWindow", "Разное"))

